### ISSUE TITLE
Use range syntax in library dependencies

### ISSUE THREAD

**Issue by ben-manes** [anurag/stripe-scala#1]
Maven (v3.0.3) does not appear to support Ivy's plus notation for selecting the latest version of a library after a start version. The range notation, e.g. [1.0,), is supported. This causes a Maven build to fail when including the library unless excludes are specified.

[ERROR] Failed to execute goal on project: Could not resolve dependencies for project: The following artifacts could not
be resolved: org.apache.httpcomponents:httpclient:jar:4.1.+, net.liftweb:lift-json_2.9.1:jar:2.+: Could not find artifact org.apache.httpcomponents:httpclient:jar:4.1.+ in scala-tools.org (http://scala-tools.org/repo-releases)

**Comment by anurag** [comment]
Thanks for reporting this - fixed in v1.0.3.
