### ISSUE TITLE
1.1.0 is not published

### ISSUE THREAD

**Issue by ornicar** [anurag/stripe-scala#10]
http://scala-tools.org/repo-releases/com/stripe/stripe-scala_2.9.1/

**Comment by ornicar** [comment]
nor is version 1.1.1.

http://repo1.maven.org/maven2/com/stripe/stripe-scala_2.9.1/

**Comment by julio73** [comment]
Any estimation on when 1.1.0 (and above) will be available on public repos? In the mean time, is the current tree version (1.1.1) usable?

**Comment by siddarth** [comment]
v1.1.2 has just been published.
