### ISSUE TITLE
ScalaTest should not be a compile-time dependency

### ISSUE THREAD

**Issue by ben-manes** [anurag/stripe-scala#2]
When trimming down my GAE war, I was surprised to see scalatest_2.9.1-1.6.1.jar in the libs. By running "mvn dependency:tree" I tracked it to this project (see below) and verified in your build file. This is a 2.6mb jar, which increases the load time of a GAE instance.

[INFO] +- com.stripe:stripe-scala_2.9.1:jar:1.0.3:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.1:compile
[INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.1.2:compile
[INFO] |  |  +- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] |  |  - commons-codec:commons-codec:jar:1.4:compile
[INFO] |  +- net.liftweb:lift-json_2.9.1:jar:2.4-M4:compile
[INFO] |  |  +- com.thoughtworks.paranamer:paranamer:jar:2.3:compile
[INFO] |  |  - org.scala-lang:scalap:jar:2.9.1:compile
[INFO] |  - org.scalatest:scalatest_2.9.1:jar:1.6.1:compile

**Comment by anurag** [comment]
Thanks, fixed in latest version (1.0.4)
